title: Web Development for Journalistic Products
description: >-
  Welcome to GitHub! We're so glad you're here. We know it can look overwhelming at first, 
  so here you will find a path to learn the basics of web development for journalistic products, 
  as part of the Messages for the Web class.
steps:
  - link: 'https://youtu.be/w3jLJU7DT5E'
    title: What is GitHub?
    description: >-
      Hey, it's your first time here, so let's not take any chances. Check out
      this short video to understand why people use GitHub.
  - course: introduction-to-github
    description: >-
      That video is pretty cool, right? If you want to learn how to use the
      workflow described in that video, take this course.
  - link: 'https://guides.github.com/introduction/git-handbook/'
    title: Git Handbook
    description: >-
      By now you are probably wondering what a Git is and why it is important in
      writing code. We have you covered with this short article on version
      control with Git.
  - course: communicating-using-markdown
    description: >-
      GitHub is all about collaboration and we collaborate in issues in pull
      requests. Learn how to get your point across with the worlds easiest text
      formatting syntax.
  - course: uploading-your-project-to-github
    description: >-
      Now that you know what GitHub does, I bet you're ready to move all of
      those projects off your local machine. This course will show you how.
  - course: introduction-to-html
    description: >-
      HTML is the markup language that forms the backbone of the internet. 
      In this course, you will build a clean, stunning webpage using HTML. 
  - course: github-pages
    description: >-
      Are you ready to make your own website with GitHub Pages? This course will 
      help you create your first website in only a few minutes.
